version: '3.5'

services:

  sample:
    container_name: sample
    image: mborne/markdown-to-html:latest
    build: .
    environment:
      - "LAYOUT=${LAYOUT}"
    labels:
      # traefik 2.x
      - "traefik.enable=true"
      - "traefik.http.routers.sample.rule=Host(`sample.${HOST_HOSTNAME}`)"
    volumes:
      - ./sample:/data:ro
    restart: unless-stopped

# see https://github.com/mborne/docker-devbox
networks:
  default:
    external:
      name: devbox
